#  Bit coin data statistical analysis

### importing the historical data of bitcoin from quandl

In [8]:
import quandl
import pickle
import pandas as pd
def get_quandl_data(quandl_id):
    '''Download and cache Quandl dataseries'''
    cache_path = '{}.pkl'.format(quandl_id).replace('/','-')
    try:
        f = open(cache_path, 'rb')
        df = pickle.load(f)   
        print('Loaded {} from cache'.format(quandl_id))
    except (OSError, IOError) as e:
        print('Downloading {} from Quandl'.format(quandl_id))
        df = quandl.get(quandl_id, returns="pandas")
        df.to_pickle(cache_path)
        print('Cached {} at {}'.format(quandl_id, cache_path))
    return df
btc_usd_price_kraken = get_quandl_data('BCHARTS/KRAKENUSD')
# considering the data of an year before the present day.
btc_usd_price_kraken = btc_usd_price_kraken.tail(365)

df = btc_usd_price_kraken.copy()
df

Loaded BCHARTS/KRAKENUSD from cache

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price
Date,,,,,,,
2019-03-10,3916.1,3916.3,3863.7,3897.9,1449.901130,5.639155e+06,3889.337949
2019-03-11,3899.8,3911.2,3815.5,3850.7,3229.684251,1.245815e+07,3857.387939
2019-03-12,3852.0,3879.6,3800.4,3863.1,3277.170766,1.261635e+07,3849.769919
2019-03-13,3864.4,3873.5,3826.2,3853.4,3013.369886,1.161036e+07,3852.947651
2019-03-14,3851.3,3907.0,3781.6,3853.9,3598.009049,1.384985e+07,3849.309765
...,...,...,...,...,...,...,...
2020-03-04,8756.6,8844.0,8670.4,8758.7,3140.280340,2.749305e+07,8754.966621
2020-03-05,8758.4,9170.0,8758.4,9066.0,4762.432910,4.296860e+07,9022.404690
2020-03-06,9065.8,9175.0,9001.9,9154.9,3664.439510,3.333930e+07,9098.063315
2020-03-07,9154.8,9213.0,8856.0,8899.5,2985.572446,2.696006e+07,9030.114350
2020-03-08,8891.1,8891.1,8882.4,8885.3,0.983851,8.743411e+03,8886.930297

### Mean and Median

In [9]:
# df['Weighted Price'].mean()
print(df.mean())

print('\n\n')

print(df.median())

Open                 8.336660e+03
High                 8.563165e+03
Low                  8.089764e+03
Close                8.350294e+03
Volume (BTC)         6.088653e+03
Volume (Currency)    5.198762e+07
Weighted Price       8.329911e+03
dtype: float64



Open                 8.526100e+03
High                 8.743600e+03
Low                  8.230300e+03
Close                8.536700e+03
Volume (BTC)         4.960814e+03
Volume (Currency)    4.179304e+07
Weighted Price       8.475875e+03
dtype: float64

In [10]:
# rounded_df = df['Open','High','Low','lose','Volume (BTC)','Volume (Currency)','Weighted Price'].round(0)
# rounded_df = df.iloc[:,:]
# print(rounded_df)
# print(rounded_df.mode())
# rounded_df = df['Open'].round(0)
# for r_df in df:
#     r_df = df.iloc[:,0:].round(0)
# print(r_df)
# r_df = r_df.mode(axis='columns', numeric_only=True)
# print(r_df)
r_df = df.round()
print(r_df)

              Open    High     Low   Close  Volume (BTC)  Volume (Currency)  \
Date
2019-03-10  3916.0  3916.0  3864.0  3898.0        1450.0          5639155.0
2019-03-11  3900.0  3911.0  3816.0  3851.0        3230.0         12458145.0
2019-03-12  3852.0  3880.0  3800.0  3863.0        3277.0         12616353.0
2019-03-13  3864.0  3874.0  3826.0  3853.0        3013.0         11610356.0
2019-03-14  3851.0  3907.0  3782.0  3854.0        3598.0         13849851.0
...            ...     ...     ...     ...           ...                ...
2020-03-04  8757.0  8844.0  8670.0  8759.0        3140.0         27493050.0
2020-03-05  8758.0  9170.0  8758.0  9066.0        4762.0         42968597.0
2020-03-06  9066.0  9175.0  9002.0  9155.0        3664.0         33339303.0
2020-03-07  9155.0  9213.0  8856.0  8900.0        2986.0         26960061.0
2020-03-08  8891.0  8891.0  8882.0  8885.0           1.0             8743.0

            Weighted Price
Date
2019-03-10          3889.0
2019-03-11          3857.0
2019-03-12          3850.0
2019-03-13          3853.0
2019-03-14          3849.0
...                    ...
2020-03-04          8755.0
2020-03-05          9022.0
2020-03-06          9098.0
2020-03-07          9030.0
2020-03-08          8887.0

[365 rows x 7 columns]

## The days on which close price was greater than median

In [11]:
cdays = df.loc[df['Close'] > 1.002726e+03]
cdays

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price
Date,,,,,,,
2019-03-10,3916.1,3916.3,3863.7,3897.9,1449.901130,5.639155e+06,3889.337949
2019-03-11,3899.8,3911.2,3815.5,3850.7,3229.684251,1.245815e+07,3857.387939
2019-03-12,3852.0,3879.6,3800.4,3863.1,3277.170766,1.261635e+07,3849.769919
2019-03-13,3864.4,3873.5,3826.2,3853.4,3013.369886,1.161036e+07,3852.947651
2019-03-14,3851.3,3907.0,3781.6,3853.9,3598.009049,1.384985e+07,3849.309765
...,...,...,...,...,...,...,...
2020-03-04,8756.6,8844.0,8670.4,8758.7,3140.280340,2.749305e+07,8754.966621
2020-03-05,8758.4,9170.0,8758.4,9066.0,4762.432910,4.296860e+07,9022.404690
2020-03-06,9065.8,9175.0,9001.9,9154.9,3664.439510,3.333930e+07,9098.063315
2020-03-07,9154.8,9213.0,8856.0,8899.5,2985.572446,2.696006e+07,9030.114350
2020-03-08,8891.1,8891.1,8882.4,8885.3,0.983851,8.743411e+03,8886.930297

### The days on which the price was higher than close price

In [12]:
pdays = df.loc[df['Close'] > df['Weighted Price']]
pdays

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price
Date,,,,,,,
2019-03-10,3916.1,3916.3,3863.7,3897.9,1449.901130,5.639155e+06,3889.337949
2019-03-12,3852.0,3879.6,3800.4,3863.1,3277.170766,1.261635e+07,3849.769919
2019-03-13,3864.4,3873.5,3826.2,3853.4,3013.369886,1.161036e+07,3852.947651
2019-03-14,3851.3,3907.0,3781.6,3853.9,3598.009049,1.384985e+07,3849.309765
2019-03-15,3853.9,3909.8,3846.8,3900.2,2890.546813,1.122124e+07,3882.046544
...,...,...,...,...,...,...,...
2020-02-28,8814.5,8895.0,8439.3,8715.5,5456.724599,4.717855e+07,8645.946629
2020-03-02,8518.8,8965.0,8486.9,8924.7,4758.565067,4.179304e+07,8782.699022
2020-03-04,8756.6,8844.0,8670.4,8758.7,3140.280340,2.749305e+07,8754.966621
2020-03-05,8758.4,9170.0,8758.4,9066.0,4762.432910,4.296860e+07,9022.404690
2020-03-06,9065.8,9175.0,9001.9,9154.9,3664.439510,3.333930e+07,9098.063315

## The days on which open was less than close

In [13]:
odays = df.loc[df['Close'] > df['Open']]
odays

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price
Date,,,,,,,
2019-03-12,3852.0,3879.6,3800.4,3863.1,3277.170766,1.261635e+07,3849.769919
2019-03-14,3851.3,3907.0,3781.6,3853.9,3598.009049,1.384985e+07,3849.309765
2019-03-15,3853.9,3909.8,3846.8,3900.2,2890.546813,1.122124e+07,3882.046544
2019-03-16,3900.1,4042.5,3899.7,3989.2,4433.965270,1.763293e+07,3976.786833
2019-03-18,3965.1,4019.9,3935.2,3969.6,3731.057533,1.481929e+07,3971.874385
...,...,...,...,...,...,...,...
2020-03-01,8526.1,8750.0,8405.0,8530.0,3134.047890,2.681391e+07,8555.680342
2020-03-02,8518.8,8965.0,8486.9,8924.7,4758.565067,4.179304e+07,8782.699022
2020-03-04,8756.6,8844.0,8670.4,8758.7,3140.280340,2.749305e+07,8754.966621
2020-03-05,8758.4,9170.0,8758.4,9066.0,4762.432910,4.296860e+07,9022.404690
2020-03-06,9065.8,9175.0,9001.9,9154.9,3664.439510,3.333930e+07,9098.063315